### ISSUE TITLE
NTFS for persistent partitions

### ISSUE THREAD

**Issue by 4rkal** [laurent85v/archuseriso#49]
There currently is not way to access COWMOS from windows because it's ext4. I would like to be able to select what partitioning scheme COWMOS uses when generating the iso.

**Comment by laurent85v** [comment]
NTFS is not a compatible file system. Persistence needs a Unix-like file system. 

If you need to share data with Windows you need to create an additional NTFS partition. To do this, when creating the USB disk, you must indicate the size of the partition dedicated to persistence in order to reserve disk space for other uses. When done create an NTFS partition on the free disk space using the tool of your choice, using gparted for example.

See the aui-mkusb command line help message for available command options.

Example with a /dev/sdc 64G usb key:
`sudo aui-mkusb --size-cow=30G aui-xfce-linux_6_4_12-0825-x64.iso /dev/sdc`

**Comment by 4rkal** [comment]
Is there any partitioning scheme that is unix like and windows can read and write to?

**Comment by laurent85v** [comment]
> Is there any file system that is unix like and windows can read and write to?

No.
NTFS has become the standard for sharing data between Linux and Windows.

> Also if I do end up creating a separate NFTS partition, how are the partitions auto mounted on archuseriso?

In the same way as for a Linux system installed on an internal hard disk, you must configure it yourself. The easiest way is to let the file manager do it for you when you click on the NTFS partition.

**Comment by 4rkal** [comment]
How is the persistent partition mounted? I need to make the NTFS partition be auto mounted by changing the archuseriso config. Fstab won't work probably so what I'm asking is how the auto mounting for the other partitions works.

**Comment by laurent85v** [comment]
>  I need to make the NTFS partition be auto mounted by changing the archuseriso config. Fstab won't work probably.

It will, just edit fstab for mouting the ntfs partition.

**Comment by laurent85v** [comment]
A script dedicated to discovering and mounting partitions could do this, it would be started as a service on startup. In any case archuseriso does not present any specific requirements for the development of such a script.
